spring:
  application:
    name: Rookiejangter
  profiles:
    active: test
  data:
    redis:
      host: redis
      port: 6379

# log file
logging:
  file:
    path: logs

image:
  upload:
    dir: src/main/resources/images/

jwt:
  secret: "64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff"